volumes:
  rss-data:

services:
  rss-generator:
    image: denoland/deno:alpine
    volumes:
      - rss-data:/app/rss

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - rss-data:/usr/share/nginx/html:ro
    depends_on:
      - rss-generator
